ServeShare/ServeShare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('jobs/', include('jobs.urls')),
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ServeShare/core/urls.py
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('leaderboard',views.leaderboard,name='leaderboard')
]

ServeShare/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register-volunteer",views.register_volunteer,name='register_volunteer'),
    path("register-organization",views.register_organization,name='register_organization'),
    path("login",views.login_user,name='login'),
    path("logout",views.logout_user,name='logout'),
    path("MyProfile",views.my_profile,name='my_profile'),
    path("<int:user_id>",views.profile_view,name='profile_view'),
]

ServeShare/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import transaction
from .models import OrganizationProfile,VolunteerProfile
from category.models import Category
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class VolunteerSignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    interests = forms.ModelMultipleChoiceField(required=False,
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'checkbox-group'})
    )
    profile_picture = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')   

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_volunteer = True
        if commit:
            user.save()
        volunteer = VolunteerProfile.objects.create(user=user, 
                                                   bio=self.cleaned_data.get('bio'),
                                                   first_name=self.cleaned_data.get('first_name'),
                                                   last_name=self.cleaned_data.get('last_name'),
                                                   profile_picture=self.cleaned_data.get('profile_picture'),
                                                   city=self.cleaned_data.get('city'),
                                                   state=self.cleaned_data.get('state'),
                                                   country=self.cleaned_data.get('country'))
        volunteer.interests.set(self.cleaned_data.get('interests'))
        return user


class OrganizationSignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    website = forms.URLField(widget=forms.URLInput(attrs={'class': 'form-control'}))
    established_year = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    causes_supported = forms.ModelMultipleChoiceField(required=False,
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'checkbox-group'})
    )
    logo_picture = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')   

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_organization = True
        if commit:
            user.save()
        organization = OrganizationProfile.objects.create(user=user, 
                                                   phone_number=self.cleaned_data.get('phone_number'),
                                                   description=self.cleaned_data.get('description'),
                                                   address=self.cleaned_data.get('address'),
                                                   logo_picture=self.cleaned_data.get('logo_picture'),
                                                   website=self.cleaned_data.get('website'),
                                                   established_year=self.cleaned_data.get('established_year'),
                                                   name=self.cleaned_data.get('name'),
                                                   city=self.cleaned_data.get('city'),
                                                   state=self.cleaned_data.get('state'),
                                                   country=self.cleaned_data.get('country'))
        organization.causes_supported.set(self.cleaned_data.get('causes_supported'))
        return user

ServeShare/users/views.py
from django.shortcuts import render,redirect
from .forms import OrganizationSignUpForm,VolunteerSignUpForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from category.models import Category,Badge
# from jobs.models import job_post

User = get_user_model()
# Create your views here.

def register_organization(request):
    if request.method == "POST":
        form = OrganizationSignUpForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            request.user.organization.following.add(request.user.organization)
            return redirect('core:index')
    else:
        form = OrganizationSignUpForm()
    return render(request,'users/register_organisation.html',({'form':form}))

def register_volunteer(request):
    if request.method == "POST":
        form = VolunteerSignUpForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            request.user.volunteer.following.add(request.user)
            return redirect('core:index')
    else:
        form = VolunteerSignUpForm()
    return render(request,'users/register_volunteer.html',({'form':form}))

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect("core:index")
        else:
            messages.success(request,("Enter correct username and password"))
            return redirect("users:login")
    else:
        
        return render(request,"users/login_user.html")   
    
@login_required(login_url='users/login')
def logout_user(request):
    logout(request)
    return redirect('core:index')

@login_required(login_url='/users/login')
def my_profile(request):
    jobs = request.user.jobs_by.all()
    if request.user.is_volunteer:
        followers_count = request.user.followed_by_volunteers.all().count()
        follow_count = request.user.volunteer.following.all().count()

        badges = Badge.objects.all()
        badge_data = []
        for badge in badges:
            events_participated = request.user.volunteer.attended_events.filter(category=badge.category).count()
            total_events = badge.required_events
            image = badge.image
            progress_percentage = (events_participated / total_events) * 100 if total_events > 0 else 0
            badge_data.append({
                'name': badge.name,
                'events_participated': events_participated,
                'total_events': total_events,
                'progress_percentage': progress_percentage,
                "image":image,
            })

        context = {
            "followers": followers_count,
            "following": follow_count,
            "jobs":jobs,
            "badges": badge_data,  # Pass the badge data list to the context
        }
        return render(request, 'users/profile.html', context)

    if request.user.is_organization:
        followers_count = request.user.organization.followed_by_org.all().count()
        follow_count = request.user.organization.following.all().count()
        return render(request,'users/org_profile.html',({"followers":followers_count,"following":follow_count,"jobs":jobs}))
    

def profile_view(request,user_id):
    u = User.objects.get(pk = user_id)
    if request.user == u:
        jobs = request.user.jobs_by.all()
        if request.user.is_volunteer:
            followers_count = request.user.followed_by_volunteers.all().count()
            follow_count = request.user.volunteer.following.all().count()

            badges = Badge.objects.all()
            badge_data = []
            for badge in badges:
                events_participated = request.user.volunteer.attended_events.filter(category=badge.category).count()
                total_events = badge.required_events
                image = badge.image
                progress_percentage = (events_participated / total_events) * 100 if total_events > 0 else 0
                badge_data.append({
                    'name': badge.name,
                    'events_participated': events_participated,
                    'total_events': total_events,
                    'progress_percentage': progress_percentage,
                    "image":image,
                })

            context = {
                "followers": followers_count,
                "following": follow_count,
                "jobs":jobs,
                "badges": badge_data,  # Pass the badge data list to the context
            }
            return render(request, 'users/profile.html', context)

        if request.user.is_organization:
            followers_count = request.user.organization.followed_by_org.all().count()
            follow_count = request.user.organization.following.all().count()
            return render(request,'users/org_profile.html',({"followers":followers_count,"following":follow_count,"jobs":jobs}))

    if u.is_volunteer:
        followers_count = u.followed_by_volunteers.all().count()
        follow_count = u.volunteer.following.all().count()
        if request.method == "POST":
            if 'follow' in request.POST:
                key = request.POST.get('follow')
                utf = User.objects.get(pk=key)
                request.user.volunteer.following.add(utf)
                request.user.save()
            if 'unfollow' in request.POST:
                key = request.POST.get('unfollow')
                utf = User.objects.get(pk=key)
                request.user.volunteer.following.remove(utf)
                request.user.save()
        return render(request,'users/vol_profile.html',({'u':u,"followers":followers_count,"following":follow_count}))
    if u.is_organization:
        followers_count = u.organization.followed_by_org.all().count()
        follow_count = u.organization.following.all().count()
        if request.method == "POST":
            if request.user.is_volunteer:
                if 'follow' in request.POST:
                    key = request.POST.get('follow')
                    utf = User.objects.get(pk=key)
                    request.user.volunteer.following.add(utf)
                    request.user.save()
                if 'unfollow' in request.POST:
                    key = request.POST.get('unfollow')
                    utf = User.objects.get(pk=key)
                    request.user.volunteer.following.remove(utf)
                    request.user.volunteer.save()
            if request.user.is_organization:
                if 'followo' in request.POST:
                    key = request.POST.get('followo')
                    utf = User.objects.get(pk=key)
                    request.user.organization.following.add(utf.organization)
                    request.user.save()
                if 'unfollowo' in request.POST:
                    key = request.POST.get('unfollowo')
                    utf = User.objects.get(pk=key)
                    request.user.organization.following.remove(utf.organization)
                    request.user.organization.save()
        return render(request,'users/organ_profile.html',({'u':u,"followers":followers_count,"following":follow_count}))

ServeShare/users/templates/users/login_user.html
{% extends 'base.html' %}

{% block content %}
<div class="container bg-light p-4 rounded login-box mt-1">
    {% if messages %}
        {% for msg in messages %}

            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <div class="width-hund">
        <div class="container-sm form-box login">
            <div class="log-in">Login</div>
            <br/><br/>
            <form action="{% url 'users:login' %}" method="post" >
                {% csrf_token %}
                <div class="mb-3 input-box">
                    <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
                    {% comment %} <label for="exampleInputEmail1" class="form-label">Username</label> {% endcomment %}
                    <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
                    <label for="email">Username</label>
                </div>
                <div class="mb-3 input-box">
                    <span class="icon"><ion-icon name="lock-closed-outline"></ion-icon>
                    </span>
                    {% comment %} <label for="exampleInputPassword1" class="form-label">Password</label> {% endcomment %}
                    <input type="password" class="form-control" name= "password" id="exampleInputPassword1">
                    <label for="password">Password</label>
                </div>
                    {% comment %} <input type="submit" value="Submit" class="btn btn-secondary"> {% endcomment %}
                    <button type="submit" class="btn btn-secondary">Submit</button>
            </form>
        </div>
    </div>

    <div class="login-register">
        <p>Don't have an account? <br>
            <ul>
                <li>
                    <a class="register-link" href="{% url 'users:register_volunteer' %}">Register as Volunteer</a>
                </li>
                <li>
                    <a class="register-link" href="{% url 'users:register_organization' %}">Register as Organisation</a>
                </li>
            </ul>    
        </p>
    </div>
</div>
{% endblock content %}
<div class="form-box login">
    <h2>Login</h2>
    <form action="#">
        <div class="input-box">
            <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
            <input type="email" required>
            <label for="email">Email</label>
        </div>
        <div class="input-box">
            <span class="icon"><ion-icon name="lock-closed-outline"></ion-icon>
            </span>
            <input type="password" required>
            <label for="password">Password</label>
        </div>
        <div class="remember-forget">
            <label><input type="checkbox">Remember Me</label>
            <a href="#">Forget Password</a>
        </div>
        <button type="submit" class="btn">Login</button>
        <div class="login-register">
            <p>Don't have an account?<a href="#" class="register-link">Register</a></p>
        </div>
    </form>
</div>

ServeShare/users/templates/users/organ_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
        <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" href="{% static 'css/cfc.css' %}">
        <link rel="stylesheet" href="{% static 'css/events.css' %}">
        <link rel="stylesheet" href="{% static 'css/profile.css' %}">
        <link rel="stylesheet" href="{% static 'css/post1.css' %}">
        <title>ServeShare</title>
</head>

<body style="overflow: auto">
    <!-- NavBar -->
    {% include 'navbar.html' %}
    <div class="d-flex position-relative flex-column">
        <div class="events d-flex p-4 ms-5 justify-content-center align-items-center post-1" style="height: 90vh;">
    
            <div class="scrolling ms-5 p-0" style="height: 100%; width: 93vw">

                <div class="row">
                    <div class="col-lg-4">
                        <div class="card border mb-4">
                            <div class="card-body text-center">
                                <img src="{{u.organization.logo_picture.url}}" alt="avatar" class="rounded-circle img-fluid"
                                    style="width: 150px;">
                                <h5 class="my-3">{{u.username}}</h5>
                                <p class="text-muted mb-1">Joined:{{u.organization.joining_date}}</p>
                                <p class="text-muted mb-4">{{following}} Following/ {{followers}} Followers</p>
                                <div class="d-flex justify-content-center mb-2">
                                    {% if user.is_volunteer %}
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {% if u in user.volunteer.following.all %}
                                        <button class="btn btn-secondary" name="unfollow" value="{{u.id}}">Following</button>
                                        {% else %}
                                        <button class="btn btn-primary" name="follow" value="{{u.id}}">Follow</button>
                                        {% endif %}
                                    </form>
                                    {% endif %}
                                    {% if user.is_organization %}
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {% if u.organization in user.organization.following.all %}
                                        <button class="btn btn-secondary" name="unfollowo" value="{{u.id}}">Following</button>
                                        {% else %}
                                        <button class="btn btn-primary" name="followo" value="{{u.id}}">Follow</button>
                                        {% endif %}
                                    </form>
                                    {% endif %}
                                    <!-- <button type="button" class="btn btn-outline-primary ms-1">Message</button> -->
                                </div>
                            </div>
                        </div>



                        <div class="card border mb-4 mb-lg-0">
                            <div class="card-body text-center">
                                <p class="mb-4">{{u.organization.description}}</p>
                            </div>
                        </div>


                        <div class="card border mb-4  align-items-center">
                            <div class="card-body text-center">
                                <h5>Donate Us</h5>
                                <div class="container-fluid d-flex flex-column scrolling pt-3" style="height: 40vh; width: 40vh;">
                                    <img src="https://source.unsplash.com/random/80×80" alt="">
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="col-lg-8">
                        <div class="col-lg-5">
                            

                            <div class="col-lg-5" style="background-color: white;">

                                <div class="bg-light" style=" width: 47.5vw; height:35vh;">

                                    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                                        <li class="nav-item" role="presentation">
                                          <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Posts</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                          <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Events</button>
                                        </li>
                                    </ul>
    
    
                                    <div class="tab-content" id="pills-tabContent">
    
                                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                                        
                                            <div class="row row-cols-3 g-3 p-3">
                                                {% for post in u.posts.all %}
                                                <img src="{{post.image.url}}" alt="">
                                                {% endfor %}
                                            </div>

                                        </div>
    
                                         <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
                                            
                                            <div class="row row-cols-3 g-3 p-3">
                                                {% for event in u.organization.events.all  %}
                                                <img src="{{event.image.url}}" alt="">
                                                {% endfor %}
                                            </div>
    
                                        </div>
    
                                    </div>

                                </div>


                            </div>

                        </div>

                        
                        
                    </div>

                </div>

            </div>

            

            

        <div class="sidebar position-absolute z-2" id="sidebar">
            {% include 'sidebar.html' %}
        </div>        
    </div>


    <div class="border-top border-bottom ps-5" style="background-color: rgba(0, 0, 0, 0.03);">
       <div class="d-flex flex-column">
         <!-- Section: Links  -->
         <section class="pt-2">
            <div class="px-3 text-start">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold">
                            <i class="fas fa-gem me-3"></i>ServeShare
                        </h6>
                        <p>
                            Welcome to ServeShare, where purpose meets action. Join our vibrant
                            community bridging volunteers and NGOs for impactful collaborations.
                            Empower change, share your skills, and make a difference together
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Upcoming Events

                        </h6>
                    </div>


                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Quick links
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Home</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">LeaderBoard</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Blogs</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Community</a>
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-2 col-xl-2">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">Join us</h6>
                        <p>
                            <a href="" class="me-4 text-reset">
                                Donate
                            </a>
                        </p>

                        <!-- Grid column -->
                    </div>
                    <!-- Grid row -->
                </div>
        </section>
        <!-- Section: Links  -->

        <!-- Copyright -->
        <div class="text-center py-2">
            © 2023 Copyright
        </div>
        <!-- Copyright -->
       </div>
    </div>
   
    


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="{% static 'js/sidebar.js' %}"></script>
    <script src="{% static 'js/cfc.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

ServeShare/users/templates/users/register_organisation.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid bg-light rounded"  >
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        There was an error with your registration...
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <h1>Register</h1>
    <br/><br/>
    <form action="{% url 'users:register_organization' %}" method=POST enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" class="btn btn-secondary">
        </form>
    </div>  
{% endblock content %}

ServeShare/users/templates/users/register_volunteer.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        There was an error with your registration...
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <h1>Register</h1>
    <br/><br/>
    <form action="{% url 'users:register_volunteer' %}" method=POST enctype="multipart/form-data">
        {% csrf_token %}
            {{form.as_p}}
         <input type="submit" value="Submit" class="btn btn-secondary">
    </form>
</div>
{% endblock content %}