ServeShare/ServeShare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('jobs/', include('jobs.urls')),
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ServeShare/core/urls.py
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('leaderboard',views.leaderboard,name='leaderboard')
]

ServeShare/jobs/urls.py
from django.urls import path
from . import views
app_name = 'jobs'

urlpatterns = [
    path('post-job',views.post_job,name='post_job'),
    path('new-jobs',views.jobs,name='new_jobs'),
    path('<int:job_id>',views.job_desc,name='details'),
    # url pattern for approving and disaaproving applicant
    path('job/<int:job_id>/approve/<int:user_id>/', views.approve_applicant, name='approve_applicant'),
    path('job/<int:job_id>/disapprove/<int:user_id>/', views.disapprove_applicant, name='disapprove_applicant'),
]

ServeShare/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('post',views.normal_post,name='normal_post'),
    path('event-post',views.event_post,name='event_post'),
]

ServeShare/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register-volunteer",views.register_volunteer,name='register_volunteer'),
    path("register-organization",views.register_organization,name='register_organization'),
    path("login",views.login_user,name='login'),
    path("logout",views.logout_user,name='logout'),
    path("MyProfile",views.my_profile,name='my_profile'),
    path("<int:user_id>",views.profile_view,name='profile_view'),
]

ServeShare/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
        <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
        <link rel="stylesheet" href="{% static 'css/leaderboard.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" href="{% static 'css/cfc.css' %}">
        <link rel="stylesheet" href="{% static 'css/events.css' %}">
        <link rel="stylesheet" href="{% static 'css/post1.css' %}">
        <link rel="stylesheet" href="{% static 'css/login_user.css' %}">

        <title>ServeShare</title>
</head>

<body>
    <!-- NavBar -->
    {% include 'navbar.html' %}
    <div class="d-flex position-relative">
        <div class="events d-flex p-4 justify-content-center align-items-center post-1">
    
                {% block content %}
                
                {% endblock content %}

        <div class="sidebar position-absolute z-2" id="sidebar">
            {% include 'sidebar.html' %}
        </div>        
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="{% static 'js/sidebar.js' %}"></script>
    <script src="{% static 'js/cfc.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

ServeShare/templates/base2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomePage</title>
    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer">

    <style>
        .bg-blue {
            background-color: #00BBFF;
        }

        .p-custom {
            padding-right: 95px; /* Adjusted padding */
        }

        .h-custom {
            height: 92.5vh;
        }

        .scrolling {
            height: 80vh;
            overflow: auto;
        }

        .scrolling::-webkit-scrollbar {
            width: 0.5em;
        }

        .scrolling::-webkit-scrollbar-track {
            background-color: transparent;
        }

        .scrolling::-webkit-scrollbar-thumb {
            background-color: transparent;
        }
    </style>

    <link rel="stylesheet" href="index.css">

</head>

<body>

    <!-- ~~~~~~~~~~~~~~~~~~ Navbar-Start ~~~~~~~~~~~~~~~~~~ -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-blue">
        <div class="container pe-5">
            <a class="navbar-brand" href="{% url 'core:index' %}">ServeShare</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav d-flex gap-3">
                    <li class="nav-item active">
                        <a class="nav-link text-light" href="{% url 'core:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="abch.html">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="hsdj.html">LeaderBoard</a>
                    </li>
                    <li class="nav-item">
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search"
                                aria-label="Search">
                            <button class="btn btn-outline-primary" type="submit">Search</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- ~~~~~~~~~~~~~~~~~~ Navbar-End ~~~~~~~~~~~~~~~~~~ -->

    <!-- ~~~~~~~~~~~~~~~~~~~~~ Main-body-Start ~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="row border border-dark m-0">
        <!-- ~~~~~~~~~~~~~~~~~~~~~ Sidebar-Start ~~~~~~~~~~~~~~~~~~~~~~ -->
        <div class="col-11 p-custom">
            <div class="m-0 p-0 h-custom">
                <div class="scrolling p-2" style="height: 90vh;">
                    <!-- ~~~~~~~~~~~~~~~~~~~~~ Main-Content-Start ~~~~~~~~~~~~~~~~~~~~~~ -->
                     {% block content %}{% endblock content %}

                    <div class="container-fluid border border-danger">
                        
                    </div>

                    <!-- ~~~~~~~~~~~~~~~~~~~~~ Main-Content-End ~~~~~~~~~~~~~~~~~~~~~~ -->
                </div>
            </div>
        </div>
        <!-- ~~~~~~~~~~~~~~~~~~~~~ Sidebar-End ~~~~~~~~~~~~~~~~~~~~~~ -->

        <div class="col-1">
            <div class="row">
                <div class="col-lg-8 col-md-4 col-sm-1">
                    <!-- Empty space for alignment -->
                </div>
                <div class="col-lg-4 col-md-8 col-sm-11 bg-blue h-custom d-flex flex-column justify-content-start align-items-center">
                    <a href="#"><i class="fa-solid fa-user mt-5 link-dark"></i></a>
                    <a href="#"><i class="fa-solid fa-plus mt-5 link-dark"></i></a>
                    <a href="#"><i class="fa-regular fa-calendar-plus mt-5 link-dark"></i></a>
                    <a href="#"><i class="fa-solid fa-shoe-prints fa-rotate-270 mt-5 link-dark"></i></a>
                    <a href="#"><i class="fa-solid fa-bars mt-5 link-dark"></i></a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}"><i class="fa-solid fa-right-from-bracket mt-5 link-dark"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- ~~~~~~~~~~~~~~~~~~~~~ Sidebar-End ~~~~~~~~~~~~~~~~~~~~~~ -->
    </div>
    <!-- ~~~~~~~~~~~~~~~~~~~~~ Main-body-End ~~~~~~~~~~~~~~~~~~~~~~ -->

    <!-- Link to Bootstrap JS (Popper.js and Bootstrap JS are required) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>

</html>

ServeShare/templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top" style="background-color: #00BBFF;">
    <div class="container-fluid">
        <a class="navbar-brand ms-5" style="color: white;" href="/">ServeShare</a>
        <button class="navbar-toggler border-dark" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="justify-content-center align-items-center"><ion-icon name="menu" class="me-0 ms-0"></ion-icon></span>
        </button>
        <div class="collapse navbar-collapse justify-content-start" id="navbarSupportedContent">
            <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" style="color: white;" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: white;" href="{% url 'jobs:new_jobs' %}">Jobs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: white;" href="{% url 'core:leaderboard' %}">Leader Board</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

ServeShare/templates/sidebar.html
<div class="sidebar-container ">
    <div class="container-sm d-flex justify-content-start align-items-center rounded-start sidebar-1" style="background-color: #00BBFF;">
        <div class="mer p-3 ps-1">
            <div class="rounded-start option p-2">
                <a class="d-flex justify-content-start align-items-center text-decoration-none text-dark user" href="{% url 'users:my_profile' %}">
                    <ion-icon name="person"></ion-icon>
                    <div class="sidebar-text ms-4 rounded-end option p-1">User</div>
                </a>
            </div>
            {% if user.is_organization %}
            <div class="rounded-start option p-2">
                <a class="d-flex justify-content-start align-items-center text-decoration-none text-dark addUser" href="{% url 'posts:event_post' %}">
                    <ion-icon name="add"></ion-icon>
                    <div class="sidebar-text ms-4 rounded-end option p-1">Add Event</div>
                </a>
            </div>
            {% endif %}
            <div class="rounded-start option p-2">
                <a class="d-flex justify-content-start align-items-center text-decoration-none text-dark addUser" href="{% url 'posts:normal_post' %}">
                    <ion-icon name="add-circle"></ion-icon>
                    <div class="sidebar-text ms-4 rounded-end option p-1">Add Post</div>
                </a>
            </div>
            <div class="rounded-start option p-2">
                <a class="d-flex justify-content-start align-items-center text-decoration-none text-dark calender" href="{% url 'jobs:post_job' %}">
                    <ion-icon name="journal"></ion-icon>
                    <div class="sidebar-text ms-4 rounded-end option p-1">Add Job</div>
                </a>
            </div>
            <div class="option rounded-start option-fp p-2">
                <a class="d-flex justify-content-start align-items-center text-decoration-none text-dark cfc" href="#">
                    <ion-icon name="footsteps"></ion-icon>
                    <div class="sidebar-text ms-4 rounded-end option-fp p-1">Carbon Foot Print</div>
                </a>
            </div>
            {% if user.is_authenticated %}
            <div class="option rounded-start option p-2">
                <a class="d-flex justify-content-start align-items-center text-decoration-none text-dark log-out" href="{% url 'users:logout' %}">
                    <ion-icon name="log-out"></ion-icon>
                    <div class="sidebar-text ms-4 rounded-end option p-1">Log Out</div>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="popup-container me-0 rounded">
        <div class="container-sm p-3">
            <span class="icon-close"><ion-icon name="close-outline"></ion-icon></span>
            <div class="col-lg-12 mt-5 p-2 mt-lg-0 d-flex align-items-stretch rounded wrapper"
                style="background-color: white;">
                <div class="container-fluid form-box d-block">
                    <div class="d-flex justify-content-start align-items-center">
                        <ion-icon name="leaf" style="font-size: 1.5em;"></ion-icon><h3 class="ms-2">Calculate your FootPrint here</h3><br>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="name">Enter Your Electricity Bill</label>
                            <input type="number" name="name" class="form-control" id="eb" required>
                        </div>
                        <div class="form-group col-md-6 mt-3 mt-md-0">
                            <label for="name">Enter Your Gas Bill</label>
                            <input type="number" class="form-control" name="email" id="gb" required>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="form-group col-md-6 mt-3 mt-md-0">
                            <label for="name">How Much Km's You Drove ?</label>
                            <input type="number" class="form-control" name="email" id="km" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="name">Number of Flights taken</label>
                            <input type="number" name="name" class="form-control" id="a4" required>
                        </div>
                    </div>
                    <br>
                    <div class="input-group mb-3 rounded">
                        <span class="lab">Do you recycle your Newspaper</span>
                        <span class="form-check m-2">
                            <input class="form-check-input" style="color: green;" type="radio" name="newsp"
                                id="flexRadioDefault1" value="yes">
                            <label class="form-check-label" for="flexRadioDefault1">
                                Yes
                            </label>
                        </span>
                        <span class="form-check m-2">
                            <input class="form-check-input" type="radio" name="newsp" id="flexRadioDefault2"
                                value="no">
                            <label class="form-check-label" for="flexRadioDefault2">
                                No
                            </label>
                        </span>
                    </div>
                    <div class="input-group mb-3 rounded">
                        <span class="lab">Do you recycle Metal Scrap</span>
                        <span class="form-check m-2">
                            <input class="form-check-input" type="radio" name="mesc" id="flexRadioDefault1"
                                value="yes">
                            <label class="form-check-label" for="flexRadioDefault1">
                                Yes
                            </label>
                        </span>
                        <span class="form-check m-2">
                            <input class="form-check-input" type="radio" name="mesc" id="flexRadioDefault2"
                                value="no">
                            <label class="form-check-label" for="flexRadioDefault2">
                                No
                            </label>
                        </span>
                    </div>
                    <div class="my-3">
                        <div>YOUR CF COUNT IS : <span id="ans"></span></div>
                    </div>
                    <div class="text-center"><button type="button" onclick="find()" id="button"
                            class="btn btn-lg btn-custom">Calculate</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>