ServeShare/ServeShare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('jobs/', include('jobs.urls')),
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ServeShare/core/urls.py
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('leaderboard',views.leaderboard,name='leaderboard')
]

ServeShare/jobs/urls.py
from django.urls import path
from . import views
app_name = 'jobs'

urlpatterns = [
    path('post-job',views.post_job,name='post_job'),
    path('new-jobs',views.jobs,name='new_jobs'),
    path('<int:job_id>',views.job_desc,name='details'),
    # url pattern for approving and disaaproving applicant
    path('job/<int:job_id>/approve/<int:user_id>/', views.approve_applicant, name='approve_applicant'),
    path('job/<int:job_id>/disapprove/<int:user_id>/', views.disapprove_applicant, name='disapprove_applicant'),
]

ServeShare/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("register-volunteer",views.register_volunteer,name='register_volunteer'),
    path("register-organization",views.register_organization,name='register_organization'),
    path("login",views.login_user,name='login'),
    path("logout",views.logout_user,name='logout'),
    path("MyProfile",views.my_profile,name='my_profile'),
    path("<int:user_id>",views.profile_view,name='profile_view'),
]

ServeShare/jobs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from users.models import VolunteerProfile

User = get_user_model()
# Create your models here.
class job_post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    venue = models.CharField(max_length=200)
    compensation = models.DecimalField(max_digits=10, decimal_places=2)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE,related_name='jobs_by')
    created_at = models.DateTimeField(auto_now_add=True)
    approved = models.ManyToManyField(VolunteerProfile,related_name="my_jobs")

    def __str__(self):
        return self.title
    
class applicants(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="my_applications")
    for_job =models.ForeignKey(job_post,on_delete=models.CASCADE,related_name="applicants")
    email = models.EmailField()
    phno = models.CharField(max_length=10) 

ServeShare/jobs/forms.py
from django import forms
from .models import job_post,applicants


class job_post_form(forms.ModelForm):
    
    class Meta:
        model = job_post
        fields = ("title", "description", "venue", "compensation")
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add Bootstrap classes to form fields
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['venue'].widget.attrs.update({'class': 'form-control'})
        self.fields['compensation'].widget.attrs.update({'class': 'form-control'})


        

ServeShare/jobs/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import job_post_form
from django.contrib.auth.decorators import login_required
from .models import job_post,applicants
from django.contrib.auth import get_user_model

User =  get_user_model()
# Create your views here.
@login_required(login_url='/users/login')
def post_job(request):
    if request.method == 'POST':
        form1 = job_post_form(request.POST)
        if form1.is_valid():
            job = form1.save(commit=False)
            job.posted_by= request.user
            job.save()
            return redirect('core:index')
    form1 = job_post_form
    return render(request,'jobs/post_job.html',({"job_form":form1}))

def jobs(request):
    jobs = job_post.objects.all().order_by('-created_at') 
    return render(request,'jobs/new_jobs.html',({"jobs":jobs}))

def job_desc(request,job_id):
    job = job_post.objects.get(pk = job_id)
    is_applicant = applicants.objects.filter(user=request.user, for_job=job).exists()
    if request.user.is_volunteer:
        if request.method == 'POST':
            ph = request.POST.get("phone")
            em = request.POST.get("email")
            u = request.user
            app = applicants.objects.create(user=u,for_job=job,email=em,phno=ph)
            app.save()
            return redirect('jobs:details',job_id=job_id)
    return render(request,'jobs/desc.html',({"job":job,"bool":is_applicant}))


def approve_applicant(request, job_id, user_id):
    job = get_object_or_404(job_post, pk=job_id)
    user = get_object_or_404(User, pk=user_id)
    
    job.approved.add(user.volunteer)
    job.save()
    
    return redirect('users:my_profile')

def disapprove_applicant(request, job_id, user_id):
    job = get_object_or_404(job_post, pk=job_id)
    user = get_object_or_404(User, pk=user_id)
    
    job.approved.remove(user.volunteer)
    job.save()
    
    return redirect('users:my_profile')

ServeShare/jobs/templates/jobs/desc.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="container-fluid">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    
                    <div class="fs-3">
                        <b>{{ job.title }}</b>
                    </div>
                    
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                            <div class="d-flex justify-content-between">
                                <div>{{ job.posted_by }}</div>
                                <div>{{ job.created_at }}</div>
                            </div>
                        
                    </h5>

                    <div class="row row-cols-2 " style="margin-left: 12px;">
                         
                       
                        <div class="card-body px-0">
                            {% if bool %}
                            YOU HAVE ALREADY APPLIED!!!
                            {% else %}
                            <a type="button" class="btn btn-primary m-0" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Apply
                            </a>
                            {% endif %}
                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">Job Application</h1>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container">
                                            <form action="" method="post" >
                                                {% csrf_token %}
                                                <div class="mb-3 input-box">
                                                    <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
                                                    {% comment %} <label for="exampleInputEmail1" class="form-label">Email ID</label> {% endcomment %}
                                                    <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
                                                    <label for="email">Email ID</label>
                                                </div>
                                                <div class="mb-3 input-box">
                                                    <span class="icon"><ion-icon name="call"></ion-icon>
                                                    </span>
                                                    {% comment %} <label for="exampleInputPassword1" class="form-label">Phone Number</label> {% endcomment %}
                                                    <input type="number" class="form-control" name= "phone" id="exampleInputPassword1">
                                                    <label for="phone">Phone Number</label>
                                                </div>
                                                    <button class="btn btn-primary" type="submit" style="width: 100%;" name="apply" value="{{ job.id }}">Submit</button>
                                            </form>
                                        </div>
                                    </div>
                                  </div>
                                </div>
                            </div>
                        </div> 

                     
                    </div>
                    
                    <div class="row border"></div>
                    <div class="row border border-light" style="margin-top: 10px;">
                        <div class="card-body">
                            
                            <div class="p-1" style="background-color: white;">
                                <div class="row">
                                  <p>{{ job.description }}</p>
                                </div>
                                <div class="row">
                                  <b>Venue: {{ job.venue }}</b>
                                </div>
                                <div class="row">
                                  <b>Stipend: Rs.{{ job.compensation }}</b>
                                </div>
                            </div>
                           
                           
                        </div>


                        </div>
                        
                </div>
            </div>


        </div>
        
        </div>

    </div>
</div>

{% endblock content %}

ServeShare/jobs/templates/jobs/job_application.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">Job Application</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="container">
                <form action="{% url 'users:login' %}" method="post" >
                    {% csrf_token %}
                    <div class="mb-3 input-box">
                        <span class="icon"><ion-icon name="mail-outline"></ion-icon></span>
                        {% comment %} <label for="exampleInputEmail1" class="form-label">Email ID</label> {% endcomment %}
                        <input type="email" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
                        <label for="email">Email ID</label>
                    </div>
                    <div class="mb-3 input-box">
                        <span class="icon"><ion-icon name="call"></ion-icon>
                        </span>
                        {% comment %} <label for="exampleInputPassword1" class="form-label">Phone Number</label> {% endcomment %}
                        <input type="number" class="form-control" name= "password" id="exampleInputPassword1">
                        <label for="password">Phone Number</label>
                    </div>
                        <a class="btn btn-primary" type="submit" style="width: 100%;" name="apply" value="{{ job.id }}">Submit</a>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>

ServeShare/jobs/templates/jobs/new_jobs.html
{% extends 'base.html' %}
{% block content %}
  <div class="container text-start" style="width: 90vw">
    <h3>
        Empowering Communities: Social Services for a Better Tomorrow !!
    </h3><br>
    <div class="row row-cols-2 row-cols-lg-2 gy-4">
      {% for job in jobs %}
        <div class="accordion" id="accordionjob{{ job.id }}">
          <div class="accordion-job">
            <h2 class="accordion-header" id="heading{{ job.id }}">
              <button class="accordion-button p-2 d-block" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ job.id }}" aria-expanded="true" aria-controls="collapse{{ job.id }}">
                <div>
                  <b>{{ job.title }}</b>
                </div>
                <div class="d-flex justify-content-between">
                  <div>{{ job.posted_by }}</div>
                  <div>{{ job.created_at }}</div>
                </div>
              </button>
            </h2>
            <div id="collapse{{ job.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ job.id }}" data-bs-parent="#accordionjob{{ job.id }}">
              <div class="accordion-body p-1" style="background-color: white;">
                <div class="row">
                  <p>{{ job.description }}</p>
                </div>
                <div class="row">
                  <b>Venue: {{ job.venue }}</b>
                </div>
                <div class="row">
                  <b>Stipend: Rs.{{ job.compensation }}</b>
                </div>
                <div class="row py-1">
                  {% if user.is_volunteer %}
                    <form action="" method="POST">
                      {% csrf_token %}

                      <!-- Button trigger modal -->
                      <a href="{% url 'jobs:details' job_id=job.id %}" class="btn btn-primary">Apply</a>
                    </form>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

ServeShare/jobs/templates/jobs/post_job.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid d-flex flex-column">
    
    <h1>ADD Job</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    
    <div class="form-group">
        {{ job_form.title.label_tag }}
        {{ job_form.title }}
    </div>
    
    <div class="form-group">
        {{ job_form.description.label_tag }}
        {{ job_form.description }}
    </div>
    
    <div class="form-group">
        {{ job_form.venue.label_tag }}
        {{ job_form.venue }}
    </div>
    
    <div class="form-group">
        {{ job_form.compensation.label_tag }}
        {{ job_form.compensation }}
    </div>
    
    <button type="submit" class="btn btn-primary">Post Job</button>
</form>

</div>
{% endblock content %}